
# MQTT broker details
BROKER_IP   = "95.94.45.83"
BROKER_PORT = 1883
BROKER_USER = "pi"
BROKER_PASSWORD = "vfpYcu8BVUB26kgtk73sADxYVJ2O3URc62SWs80n"

# TOPICS

TOPIC_TEMP = "temperature"
TOPIC_LEVEL = "water-level"
TOPIC_TOKEN = "validate-token"
TOPIC_RESPONSE = "response-token"

# SUBSCRIPTIONS
SUBS=[TOPIC_TEMP,TOPIC_LEVEL,TOPIC_TOKEN]